<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

class VerifyCsrfToken extends Middleware
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        'pay/wechat/notify',
        'pay/wechat/japi/notify',
        'register/vip',
        'sms/code',
    ];

//    public function handle($request, Closure $next)
//    {
//        return parent::handle($request, $next); // TODO: Change the autogenerated stub
//        return $next($request);
//    }

}
